#!/bin/bash
# Atlantic Orders API - Docker Quick Reference
# Comandos rápidos para build, run y debug

echo "======================================"
echo "Atlantic Orders API - Docker Commands"
echo "======================================"
echo ""

# ==================== BUILD ====================
echo "BUILD COMMANDS:"
echo "==============="
echo ""
echo "1. Build basic:"
echo "   docker build -t atlantic-orders-api:latest ."
echo ""
echo "2. Build sin caché (fuerza rebuild):"
echo "   docker build --no-cache -t atlantic-orders-api:latest ."
echo ""
echo "3. Build con versión:"
echo "   docker build -t atlantic-orders-api:1.0.0 ."
echo ""

# ==================== RUN ====================
echo "RUN COMMANDS:"
echo "============="
echo ""
echo "1. Run simple (BD en memoria):"
echo "   docker run -p 8080:8080 atlantic-orders-api:latest"
echo ""
echo "2. Run con .env file:"
echo "   docker run -p 8080:8080 --env-file .env atlantic-orders-api:latest"
echo ""
echo "3. Run con nombre y logs:"
echo "   docker run -d --name atlantic-api --env-file .env -p 8080:8080 atlantic-orders-api:latest"
echo "   docker logs atlantic-api -f"
echo ""
echo "4. Run con variables inline:"
echo "   docker run -p 8080:8080 \\"
echo "     -e Jwt__SecretKey='tu-clave-secreta' \\"
echo "     -e UseInMemoryDatabase='false' \\"
echo "     atlantic-orders-api:latest"
echo ""
echo "5. Run en puerto diferente:"
echo "   docker run -p 5000:8080 atlantic-orders-api:latest"
echo ""

# ==================== DOCKER COMPOSE ====================
echo "DOCKER COMPOSE COMMANDS:"
echo "======================="
echo ""
echo "1. Iniciar stack (API + SQL Server):"
echo "   docker-compose up -d"
echo ""
echo "2. Ver logs:"
echo "   docker-compose logs -f api"
echo "   docker-compose logs mssql"
echo ""
echo "3. Parar stack:"
echo "   docker-compose down"
echo ""
echo "4. Parar y eliminar volúmenes:"
echo "   docker-compose down -v"
echo ""
echo "5. Ejecutar comando en contenedor:"
echo "   docker-compose exec api dotnet --version"
echo ""
echo "6. Recrear contenedores:"
echo "   docker-compose up -d --force-recreate"
echo ""

# ==================== DEBUG ====================
echo "DEBUG COMMANDS:"
echo "=============="
echo ""
echo "1. Ver imágenes:"
echo "   docker images | grep atlantic"
echo ""
echo "2. Ver contenedores activos:"
echo "   docker ps | grep atlantic"
echo ""
echo "3. Ver estado de salud:"
echo "   docker ps -a --format 'table {{.Names}}\t{{.Status}}'"
echo ""
echo "4. Ver logs de contenedor:"
echo "   docker logs <container-id> -f --tail=50"
echo ""
echo "5. Ejecutar comando en contenedor:"
echo "   docker exec atlantic-orders-api curl http://localhost:8080/health"
echo ""
echo "6. Inspeccionar contenedor:"
echo "   docker inspect atlantic-orders-api"
echo ""
echo "7. Acceder a shell del contenedor:"
echo "   docker exec -it atlantic-orders-api /bin/bash"
echo ""

# ==================== CLEANUP ====================
echo "CLEANUP COMMANDS:"
echo "================"
echo ""
echo "1. Detener contenedor:"
echo "   docker stop atlantic-orders-api"
echo ""
echo "2. Eliminar contenedor:"
echo "   docker rm atlantic-orders-api"
echo ""
echo "3. Eliminar imagen:"
echo "   docker rmi atlantic-orders-api:latest"
echo ""
echo "4. Limpiar imágenes no usadas:"
echo "   docker image prune -a"
echo ""
echo "5. Limpiar volúmenes no usados:"
echo "   docker volume prune"
echo ""
echo "6. Limpiar todo (cuidado):"
echo "   docker system prune -a --volumes"
echo ""

# ==================== TESTING ====================
echo "TESTING COMMANDS:"
echo "================"
echo ""
echo "1. Verificar salud de API:"
echo "   curl http://localhost:8080/health"
echo ""
echo "2. Obtener token JWT:"
echo "   curl -X POST http://localhost:8080/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"usuario\":\"admin\",\"contrasena\":\"admin123\"}'"
echo ""
echo "3. Obtener todos los pedidos:"
echo "   curl http://localhost:8080/api/pedidos \\"
echo "     -H 'Authorization: Bearer [TOKEN]'"
echo ""
echo "4. Acceder a Swagger:"
echo "   http://localhost:8080/swagger/index.html"
echo ""

# ==================== NETWORK ====================
echo "NETWORK COMMANDS:"
echo "================"
echo ""
echo "1. Ver redes:"
echo "   docker network ls"
echo ""
echo "2. Crear red:"
echo "   docker network create atlantic-net"
echo ""
echo "3. Eliminar red:"
echo "   docker network rm atlantic-net"
echo ""
echo "4. Ver contenedores en red:"
echo "   docker network inspect atlantic-net"
echo ""

echo ""
echo "======================================"
echo "Para más información, consultar DOCKER.md"
echo "======================================"
